$(document).ready(function(){var elem_por_pagina=11;var url_string=window.location.href;var url=new URL(url_string);var pag_actual=url.searchParams.get("pagina");var inicio;if(pag_actual==null){pag_actual=1}
var c=url.searchParams.get("busqueda_lista");if(c==undefined){window.location="home.html"}
document.title="Búsqueda listas: "+c;$("#texto_nombre_busqueda").append("\""+c+"\"");var jsonData=JSON.parse(JSON.parse(sessionStorage.getItem("lista_listas")));var listas=jsonData.busquedaListas;if(listas!=undefined){var inicio=(pag_actual-1)*elem_por_pagina;var sin_elementos=1;var no=0;var si=1;var aux=[];for(j in listas){if(listas[j].nombre!="Favoritos"){aux.push(listas[j])}}
listas=aux;for(i=inicio;i<(elem_por_pagina+inicio)&&i<listas.length;i++){var lista=listas[i].nombre;var autor=listas[i].nombreUsuario;if("Favoritos"!=lista){var large='<div class="cancioninf"><ul><li id="barraopciones"><a href="lista.html'+"?lista="+lista+'&autor='+autor+'" id="enlacecancion"><div class="imagen"><img src="img/listaicono.png" alt="Imagen lista"></div></a></li><li id="barraopciones"><a href="lista.html'+"?lista="+lista+'&autor='+autor+'"><div class="nombrecancion">'+lista+'</div><div class="nombreautor">Autor: '+autor+'</div></a></li>';var repr_lista='<li id="barraopciones"><form class="form_reproducir_lista" method="post" action="/ps/VerLista"><div class="simb_repr_play"><input type="image" src="img/play.png" alt="Reproducir lista" title="Reproducir lista"><input type="hidden" name="nombreLista" value="'+lista+'"/><input type="hidden" name="nombreCreadorLista" value="'+autor+'"/></div></form></li>';var resto='</ul></div>';$(".informacion").append(large+repr_lista+resto);sin_elementos=0}}
if(sin_elementos==1){$("#titulopagina").after("<h2 id=\"sin_resul\">No hay resultados.</h2>")}
else if((elem_por_pagina+inicio)<listas.length){var pagina_sig=parseInt(pag_actual)+1;var boton_mas='<br><br><form action="busqueda_listas.html"><button type="submit" id="boton_mostrar_mas" class="aumentar">Mostrar más</button><input type="hidden" name="busqueda_lista" value="'+c+'"/><input type="hidden" name="pagina" value="'+pagina_sig+'"/></form>';$(".informacion").append(boton_mas)}
form_repr_lista()}
else{$("#titulopagina").after("<h2 id=\"sin_resul\">No hay resultados.</h2>")}
$("#form_buscar_lista").submit(function(event){event.preventDefault();var valor_busqueda=document.getElementById("form_buscar_lista").elements[0].value;var valor_sin_espacioizquierdo=$.trim(valor_busqueda);document.getElementById("search_lista").value=valor_sin_espacioizquierdo;if(valor_sin_espacioizquierdo==""){return!1}
var post_url=$(this).attr("action");var form_data=$(this).serialize();var request_method=$(this).attr("method");$.ajax({url:post_url,type:request_method,data:form_data,}).done(function(response){var obj=JSON.parse(response);var lista_listas=JSON.stringify(response);if(obj.error!=undefined){if(obj.error.indexOf("Usuario no logeado")>=0){cerrarSesion()}
else if(obj.error.indexOf("lista cuyo nombre coincida")>=0){sessionStorage.setItem("lista_listas",lista_listas);window.location="busqueda_listas.html?busqueda_lista="+valor_sin_espacioizquierdo+"&pagina=1"}
else{alert("Error. Inténtelo más tarde.")}}
else{sessionStorage.setItem("lista_listas",lista_listas);window.location="busqueda_listas.html?busqueda_lista="+valor_sin_espacioizquierdo+"&pagina=1"}}).fail(function(response){alert("Error interno. Inténtelo más tarde.")})})})
