$(document).ready(function(){var elem_por_pagina=5;var url_string=window.location.href;var url=new URL(url_string);var pag_actual=url.searchParams.get("pagina");var inicio;document.title="Listas";$("#form_mostrar_listas").submit(function(event){event.preventDefault();document.getElementById("form_mostrar_listas").elements[0].value=leerCookie("login");var post_url=$(this).attr("action");var form_data=$(this).serialize();var request_method=$(this).attr("method");$.ajax({url:post_url,type:request_method,data:form_data,}).done(function(response){var obj=JSON.parse(response);if(obj.error!=undefined){if(obj.error.indexOf("Usuario no logeado")>=0){cerrarSesion()}
else{$("#anadir_lista").after("<h2 id=\"sin_resul\">No hay listas.</h2>")}}
else{var listas=obj.nombre;if(pag_actual==null){pag_actual=1}
else{pag_actual=parseInt(pag_actual)}
inicio=(pag_actual-1)*elem_por_pagina;var sin_elementos=1;var autor=leerCookie("login");for(i=inicio;i<(elem_por_pagina+inicio)&&i<listas.length;i++){var lista=listas[i];if("Favoritos"!=lista){var large='<div class="cancioninf"><ul><li id="barraopciones"><a href="lista.html'+"?lista="+lista+'&autor='+autor+'" id="enlacecancion"><div class="imagen"><img src="img/listaicono.png" alt="Imagen lista"></div></a></li><li id="barraopciones"><a href="lista.html'+"?lista="+lista+'&autor='+autor+'"><div class="nombrecancion">'+lista+'</div></a></li>';var repr_lista='<li id="barraopciones"><form class="form_reproducir_lista" method="post" action="/ps/VerLista"><div class="simb_repr_play"><input type="image" src="img/play.png" alt="Reproducir lista" title="Reproducir lista"><input type="hidden" name="nombreLista" value="'+lista+'"/><input type="hidden" name="nombreCreadorLista" value="'+autor+'"/></div></form></li>';var borrar_y_resto='<li id="barraopciones"><form class="form_borrar_lista" method="post" action="/ps/BorrarListaDeReproduccion"><div class="simb_repr_elim"><input type="image" src="img/eliminar.png" alt="Eliminar lista" title="Eliminar lista"></div><input type="hidden" id="seguido" name="nombreLista" value="'+lista+'"/></form></li></ul></div>';$(".informacion").append(large+repr_lista+borrar_y_resto);sin_elementos=0}}
if(sin_elementos==1){$("#anadir_lista").after("<h2 id=\"sin_resul\">No hay listas.</h2>")}
if((elem_por_pagina+inicio)<listas.length){var pagina_sig=pag_actual+1;var boton_mas='<br><br><form action="listas.html"><button type="submit" id="boton_mostrar_mas" class="aumentar">Mostrar más</button><input type="hidden" name="pagina" value="'+pagina_sig+'"/></form>';$(".informacion").append(boton_mas)}}
form_borrar_lista();form_repr_lista()}).fail(function(response){alert("Error interno. Inténtelo más tarde.")})});$("#form_mostrar_listas").submit();$("#form_crear_lista").submit(function(event){event.preventDefault();var valor_lista=document.getElementById("form_crear_lista").elements[0].value;var valor_sin_espacioizquierdo=$.trim(valor_lista);document.getElementById("IdUsar").value=valor_sin_espacioizquierdo;if(valor_sin_espacioizquierdo==""){return!1}
var post_url=$(this).attr("action");var form_data=$(this).serialize();var request_method=$(this).attr("method");$.ajax({url:post_url,type:request_method,data:form_data,}).done(function(response){var obj=JSON.parse(response);if(obj.error!=undefined){if(obj.error.indexOf("Usuario no logeado")>=0){cerrarSesion()}
else{$("#resultado_seguir").text("Ya existe la lista "+valor_sin_espacioizquierdo+".");$("#result_seguir").attr("src","img/error.png")}}
else{$("#resultado_seguir").text("Lista creada correctamente.");$("#result_seguir").attr("src","img/exito.png")}
$('.button1').click()}).fail(function(response){alert("Error interno. Inténtelo más tarde.")})});$("#form_buscar_lista").submit(function(event){event.preventDefault();var valor_busqueda=document.getElementById("form_buscar_lista").elements[0].value;var valor_sin_espacioizquierdo=$.trim(valor_busqueda);document.getElementById("search_lista").value=valor_sin_espacioizquierdo;if(valor_sin_espacioizquierdo==""){return!1}
var post_url=$(this).attr("action");var form_data=$(this).serialize();var request_method=$(this).attr("method");$.ajax({url:post_url,type:request_method,data:form_data,}).done(function(response){var obj=JSON.parse(response);var lista_listas=JSON.stringify(response);if(obj.error!=undefined){if(obj.error.indexOf("Usuario no logeado")>=0){cerrarSesion()}
else if(obj.error.indexOf("lista cuyo nombre coincida")>=0){sessionStorage.setItem("lista_listas",lista_listas);window.location="busqueda_listas.html?busqueda_lista="+valor_sin_espacioizquierdo+"&pagina=1"}
else{alert("Error. Inténtelo más tarde.")}}
else{sessionStorage.setItem("lista_listas",lista_listas);window.location="busqueda_listas.html?busqueda_lista="+valor_sin_espacioizquierdo+"&pagina=1"}}).fail(function(response){alert("Error interno. Inténtelo más tarde.")})})});function form_borrar_lista(){$(".form_borrar_lista").submit(function(event){event.preventDefault();var post_url=$(this).attr("action");var form_data=$(this).serialize();var request_method=$(this).attr("method");var lista=form_data.slice(12);$.ajax({url:post_url,type:request_method,data:form_data,}).done(function(response){var obj=JSON.parse(response);if(obj.error!=undefined){if(obj.error.indexOf("Usuario no logeado")>=0){cerrarSesion()}
else{alert("Error interno. Inténtelo más tarde.")}}
else{$("#resultado_seguir").text("Lista eliminada correctamente.");$("#result_seguir").attr("src","img/exito.png")}
$('.button1').click()}).fail(function(response){alert("Error interno. Inténtelo más tarde.")})})}
